export const TOKEN_MARKERS = [
  {
    type: "start",
    name: "Départ",
    label: "S",
    color: "#2d6eb6",
    image: "assets/tokens/base/starting-area.png",
    imageSize: [45, 39],
    product: null,
    category: "base",
    limit: null,
  },
  {
    type: "objective",
    name: "Objectif rouge",
    label: "1",
    color: "#bd343b",
    image: "assets/tokens/base/objective-red.png",
    imageSize: [22, 22],
    product: null,
    category: "base",
    limit: 10,
  },
  {
    type: "objective-blue",
    name: "Objectif bleu",
    label: "OB",
    color: "#2d6eb6",
    image: "assets/tokens/base/objective-blue.png",
    imageSize: [22, 22],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "objective-green",
    name: "Objectif vert",
    label: "OV",
    color: "#318053",
    image: "assets/tokens/base/objective-green.png",
    imageSize: [22, 22],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "invasion",
    name: "Invasion rouge",
    label: "1",
    color: "#a62d32",
    image: "assets/tokens/base/spawn-red.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 12,
  },
  {
    type: "invasion-blue",
    name: "Invasion bleue",
    label: "IB",
    color: "#2d6eb6",
    image: "assets/tokens/base/spawn-blue.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "invasion-green",
    name: "Invasion verte",
    label: "IV",
    color: "#318053",
    image: "assets/tokens/base/spawn-green.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "invasion-necromancer-beige",
    name: "Invasion Nécromancien beige",
    label: "NB",
    color: "#b69a72",
    image: "assets/tokens/base/spawn-necromancer-beige.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "invasion-necromancer-brown",
    name: "Invasion Nécromancien brune",
    label: "NM",
    color: "#795548",
    image: "assets/tokens/base/spawn-necromancer-brown.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "invasion-necromancer-green",
    name: "Invasion Nécromancien verte",
    label: "NV",
    color: "#318053",
    image: "assets/tokens/base/spawn-necromancer-green.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "invasion-necromancer-grey",
    name: "Invasion Nécromancien grise",
    label: "NG",
    color: "#70757a",
    image: "assets/tokens/base/spawn-necromancer-grey.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "invasion-necromancer-purple",
    name: "Invasion Nécromancien violette",
    label: "NP",
    color: "#7f3f98",
    image: "assets/tokens/base/spawn-necromancer-purple.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "invasion-necromancer-turquoise",
    name: "Invasion Nécromancien turquoise",
    label: "NT",
    color: "#2b9aa0",
    image: "assets/tokens/base/spawn-necromancer-turquoise.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "exit",
    name: "Sortie",
    label: "E",
    color: "#318053",
    image: "assets/tokens/base/exit-1.png",
    imageOpen: "assets/tokens/base/exit-2.png",
    imageSize: [52, 26],
    product: null,
    category: "base",
    limit: 1,
  },
  {
    type: "door",
    name: "Porte",
    label: "D",
    color: "#666c72",
    image: "assets/tokens/doors/door-closed-red.png",
    imageOpen: "assets/tokens/doors/door-open-red.png",
    imageSize: [36, 33],
    product: null,
    category: "base",
    limit: null,
  },
  {
    type: "spawn",
    name: "Nécromancien",
    label: "N",
    color: "#7f3f98",
    image: "assets/tokens/base/spawn-necromancer-purple.png",
    imageSize: [52, 27],
    product: null,
    category: "base",
    limit: null,
  },
  {
    type: "npc",
    name: "NPC cible",
    label: "N",
    color: "#7f3f98",
    product: null,
    category: "custom",
    limit: null,
  },
  {
    type: "vault",
    name: "Coffre / objectif",
    label: "C",
    color: "#a77b27",
    product: null,
    category: "custom",
    limit: null,
  },
  {
    type: "noise",
    name: "Bruit",
    label: "!",
    color: "#217d86",
    image: "assets/tokens/base/noise.png",
    imageSize: [26, 24],
    product: null,
    category: "base",
    limit: 18,
  },
  {
    type: "dragon-bile",
    name: "Bile de dragon",
    label: "BD",
    color: "#71812b",
    image: "assets/tokens/base/dragon-bile.png",
    imageSize: [52, 51],
    product: null,
    category: "base",
    limit: 4,
  },
  {
    type: "gate",
    name: "Grille",
    label: "G",
    color: "#a77b27",
    product: null,
    category: "custom",
    limit: null,
  },
  {
    type: "rubble",
    name: "Gravats",
    label: "X",
    color: "#b87416",
    product: null,
    category: "custom",
    limit: null,
  },
  {
    type: "crypt",
    name: "Zone de crypte violette",
    label: "CR",
    color: "#4d4568",
    image: "assets/tokens/black-plague/vault-purple.png",
    imageSize: [100, 100],
    product: "black-plague",
    category: "unique",
    limit: 2,
  },
  {
    type: "crypt-yellow",
    name: "Zone de crypte jaune",
    label: "CR",
    color: "#d7b33f",
    image: "assets/tokens/black-plague/vault-yellow.png",
    imageSize: [100, 100],
    product: "black-plague",
    category: "unique",
    limit: 2,
  },
  {
    type: "rotten",
    name: "Pourri",
    label: "P",
    color: "#766e42",
    image: "assets/tokens/green-horde/rotten.png",
    imageSize: [24, 24],
    product: "green-horde",
    category: "unique",
    limit: null,
  },
  {
    type: "barrier",
    name: "Barrière",
    label: "B",
    color: "#765a37",
    image: "assets/tokens/green-horde/barrier.png",
    imageSize: [81, 32],
    renderSize: 54,
    product: "green-horde",
    category: "unique",
    limit: 6,
  },
  {
    type: "hedge",
    name: "Haie",
    label: "H",
    color: "#476b31",
    image: "assets/tokens/green-horde/hedge.png",
    imageSize: [81, 32],
    renderSize: 54,
    product: "green-horde",
    category: "unique",
    limit: 6,
  },
  {
    type: "horde",
    name: "Horde",
    label: "H",
    color: "#5d6b31",
    image: "assets/tokens/green-horde/horde.png",
    imageSize: [151, 151],
    product: "green-horde",
    category: "unique",
    limit: 1,
  },
  {
    type: "trebuchet",
    name: "Trébuchet",
    label: "T",
    color: "#765a37",
    image: "assets/tokens/green-horde/trebuchet.png",
    imageSize: [49, 47],
    product: "green-horde",
    category: "unique",
    limit: null,
  },
  {
    type: "orc-abomination",
    name: "Abomination orque",
    label: "AO",
    color: "#596e36",
    image: "assets/tokens/green-horde/orc-abomination.png",
    imageSize: [50, 60],
    product: "green-horde",
    category: "unique",
    limit: null,
  },
  {
    type: "orc-fatty",
    name: "Berserker orque",
    label: "BO",
    color: "#596e36",
    image: "assets/tokens/green-horde/orc-fatty.png",
    imageSize: [38, 43],
    product: "green-horde",
    category: "unique",
    limit: null,
  },
  {
    type: "orc-necromancer",
    name: "Nécromancien orque",
    label: "NO",
    color: "#596e36",
    image: "assets/tokens/green-horde/orc-necromancer.png",
    imageSize: [35, 46],
    product: "green-horde",
    category: "unique",
    limit: null,
  },
  {
    type: "orc-runner",
    name: "Coureur orque",
    label: "CO",
    color: "#596e36",
    image: "assets/tokens/green-horde/orc-runner.png",
    imageSize: [30, 39],
    product: "green-horde",
    category: "unique",
    limit: null,
  },
  {
    type: "orc-walker",
    name: "Marcheur orque",
    label: "MO",
    color: "#596e36",
    image: "assets/tokens/green-horde/orc-walker.png",
    imageSize: [31, 42],
    product: "green-horde",
    category: "unique",
    limit: null,
  },
  {
    type: "familiar-cat",
    name: "Familier chat",
    label: "FC",
    color: "#88735b",
    image: "assets/tokens/friends-and-foes/familiar-cat.png",
    imageSize: [41, 49],
    product: "friends-and-foes",
    category: "unique",
    limit: null,
  },
  {
    type: "familiar-dog",
    name: "Familier chien",
    label: "FCh",
    color: "#88735b",
    image: "assets/tokens/friends-and-foes/familiar-dog.png",
    imageSize: [32, 39],
    product: "friends-and-foes",
    category: "unique",
    limit: null,
  },
  {
    type: "familiar-wolf",
    name: "Familier loup",
    label: "FL",
    color: "#88735b",
    image: "assets/tokens/friends-and-foes/familiar-wolf.png",
    imageSize: [45, 30],
    product: "friends-and-foes",
    category: "unique",
    limit: null,
  },
  {
    type: "tainted-abomination",
    name: "Abomination souillée",
    label: "AS",
    color: "#73594f",
    image: "assets/tokens/friends-and-foes/tainted-abomination.png",
    imageSize: [57, 57],
    product: "friends-and-foes",
    category: "unique",
    limit: null,
  },
  {
    type: "tainted-walker",
    name: "Marcheur souillé",
    label: "MS",
    color: "#73594f",
    image: "assets/tokens/friends-and-foes/tainted-walker.png",
    imageSize: [40, 47],
    product: "friends-and-foes",
    category: "unique",
    limit: null,
  },
  {
    type: "ballista",
    name: "Baliste",
    label: "BA",
    color: "#765a37",
    image: "assets/tokens/no-rest-for-wicked/ballista.png",
    imageSize: [61, 43],
    product: "no-rest-for-wicked",
    category: "unique",
    limit: null,
  },
  {
    type: "necromantic-dragon",
    name: "Dragon nécromantique",
    label: "DN",
    color: "#55616f",
    image: "assets/tokens/no-rest-for-wicked/necromantic-dragon.png",
    imageSize: [52, 75],
    renderSize: 52,
    product: "no-rest-for-wicked",
    category: "unique",
    limit: null,
  },
  {
    type: "ratz",
    name: "Nuée de rats",
    label: "R",
    color: "#665f54",
    image: "assets/tokens/no-rest-for-wicked/ratz.png",
    imageSize: [42, 44],
    product: "no-rest-for-wicked",
    category: "unique",
    limit: null,
  },
  {
    type: "spectral-walker",
    name: "Marcheur spectral",
    label: "MS",
    color: "#718293",
    image: "assets/tokens/no-rest-for-wicked/spectral-walker.png",
    imageSize: [36, 50],
    product: "no-rest-for-wicked",
    category: "unique",
    limit: null,
  },
  {
    type: "start-white-death",
    name: "Départ White Death",
    label: "DWD",
    color: "#2d6eb6",
    image: "assets/tokens/white-death/start.png",
    imageSize: [650, 324],
    product: "white-death",
    category: "unique",
    limit: null,
  },
  {
    type: "exit-white-death",
    name: "Sortie White Death",
    label: "SWD",
    color: "#c69a37",
    image: "assets/tokens/white-death/exit.png",
    imageSize: [764, 369],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "invasion-white-death-1",
    name: "Invasion White Death n°1",
    label: "1",
    color: "#a62d32",
    image: "assets/tokens/white-death/spawn-1.png",
    imageSize: [764, 369],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "invasion-white-death-2",
    name: "Invasion White Death n°2",
    label: "2",
    color: "#a62d32",
    image: "assets/tokens/white-death/spawn-2.png",
    imageSize: [764, 369],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "invasion-white-death-3",
    name: "Invasion White Death n°3",
    label: "3",
    color: "#a62d32",
    image: "assets/tokens/white-death/spawn-3.png",
    imageSize: [764, 369],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "invasion-white-death-4",
    name: "Invasion White Death n°4",
    label: "4",
    color: "#a62d32",
    image: "assets/tokens/white-death/spawn-4.png",
    imageSize: [764, 369],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "invasion-white-death-defiler",
    name: "Invasion Profanateur",
    label: "IP",
    color: "#86a63b",
    image: "assets/tokens/white-death/spawn-defiler.png",
    imageSize: [764, 369],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "white-death-flag-zone",
    name: "Zone de drapeau",
    label: "ZD",
    color: "#c69a37",
    image: "assets/tokens/white-death/flag-zone.png",
    imageSize: [764, 369],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "white-death-rope-ladder",
    name: "Échelle de corde",
    label: "EC",
    color: "#8c684d",
    image: "assets/tokens/white-death/rope-ladder.png",
    imageSize: [485, 467],
    product: "white-death",
    category: "unique",
    limit: 2,
  },
  {
    type: "white-death-cauldron",
    name: "Chaudron",
    label: "CH",
    color: "#b94f35",
    image: "assets/tokens/white-death/cauldron.png",
    imageSize: [466, 467],
    product: "white-death",
    category: "unique",
    limit: 4,
  },
  {
    type: "white-death-beacon",
    name: "Balise",
    label: "BL",
    color: "#8aa14a",
    image: "assets/tokens/white-death/beacon.png",
    imageSize: [473, 473],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "white-death-noise",
    name: "Bruit White Death",
    label: "BWD",
    color: "#d39a32",
    image: "assets/tokens/white-death/noise.png",
    imageSize: [382, 348],
    product: "white-death",
    category: "unique",
    limit: 18,
  },
  {
    type: "white-death-corruption",
    name: "Corruption",
    label: "CO",
    color: "#7dac46",
    image: "assets/tokens/white-death/corruption.png",
    imageSize: [626, 779],
    renderSize: 52,
    product: "white-death",
    category: "unique",
    limit: 15,
  },
  {
    type: "white-death-objective-red",
    name: "Objectif rouge White Death",
    label: "OR",
    color: "#bd343b",
    image: "assets/tokens/white-death/objective-red.png",
    imageSize: [569, 413],
    product: "white-death",
    category: "unique",
    limit: 11,
  },
  {
    type: "white-death-objective-green",
    name: "Objectif vert White Death",
    label: "OV",
    color: "#318053",
    image: "assets/tokens/white-death/objective-green.png",
    imageSize: [569, 413],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "white-death-objective-blue",
    name: "Objectif bleu White Death",
    label: "OB",
    color: "#2d6eb6",
    image: "assets/tokens/white-death/objective-blue.png",
    imageSize: [569, 413],
    product: "white-death",
    category: "unique",
    limit: 1,
  },
  {
    type: "guard",
    name: "Garde",
    label: "G",
    color: "#24798a",
    image: "assets/tokens/white-death/guard.png",
    imageSize: [413, 642],
    renderSize: 48,
    product: "white-death",
    category: "unique",
    limit: 12,
  },
  {
    type: "statue",
    name: "Statue de Chi",
    label: "ST",
    color: "#727981",
    image: "assets/tokens/eternal-empire/chi-statue.png",
    imageSize: [371, 576],
    renderSize: 48,
    product: "eternal-empire",
    category: "unique",
    limit: 3,
  },
  {
    type: "invasion-eternal-empire-5",
    name: "Invasion Eternal Empire n°5",
    label: "5",
    color: "#d47a32",
    image: "assets/tokens/eternal-empire/spawn-5.png",
    imageSize: [1551, 759],
    product: "eternal-empire",
    category: "unique",
    limit: 1,
  },
];

export const TOKEN_MARKER_CATEGORIES = [
  { id: "base", label: "Tokens de base" },
  { id: "custom", label: "Tokens custom" },
  { id: "unique", label: "Tokens uniques" },
];

export const INVASION_MARKERS = new Set(
  TOKEN_MARKERS.filter(
    (marker) =>
      marker.type === "invasion" || marker.type.startsWith("invasion-"),
  ).map((marker) => marker.type),
);
export const CATALOG_PREFERRED_MARKERS = new Set([
  "gate",
  "rubble",
  "barrier",
  "hedge",
]);
export const EDGE_DEFAULT_MARKERS = new Set([
  "start",
  "start-white-death",
  ...INVASION_MARKERS,
  "exit",
  "exit-white-death",
]);
export const EDGE_ANCHOR_MARKERS = new Set([
  "start",
  "start-white-death",
  ...INVASION_MARKERS,
  "exit",
  "exit-white-death",
]);
export const CELL_CENTER_MARKERS = new Set(
  TOKEN_MARKERS.map((marker) => marker.type).filter(
    (type) =>
      !["door", ...CATALOG_PREFERRED_MARKERS, ...EDGE_ANCHOR_MARKERS].includes(
        type,
      ),
  ),
);

export const ZOMBICIDE_TOKENS = {
  MARKERS: TOKEN_MARKERS,
  MARKER_CATEGORIES: TOKEN_MARKER_CATEGORIES,
  INVASION_MARKERS,
  CATALOG_PREFERRED_MARKERS,
  EDGE_DEFAULT_MARKERS,
  EDGE_ANCHOR_MARKERS,
  CELL_CENTER_MARKERS,
};
